# dev or release, dev是开发模式, 会打印更多日志, 使用测试数据库和相关配置,
# dev相关配置会在dev命名空间下, release相关配置会在默认命名空间下, 最终配置是合并后的结果, 相同配置项dev优先
# dev模式时log level为debug， release模式时为设定值
mode: dev

# mysql 配置 用于存储访问和短链信息
mysql:
  host: localhost
  port: 3306
  username: root
  password: password
  database: short_link_sys
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 60 # minute

# 本服务将会监听什么地址和端口
server:
  host: localhost
  port: 8081

# log等级和存储地址
log:
  level: debug # debug, info, warn, error, fatal, panic
  path: ./log

# 转发服务器地址和端口
core:
  host: localhost
  port: 28081
  authToken: token

# handler相关配置
handler:
  link:
    minLength: 6
    algorithm: simpleSeq # murmurHash, xxHash, fnvHash, simpleSeq, snowflakeSeq
    bloomFilter: # 布隆过滤器配置, 若算法是哈希算法, 则必须配置
      falsePositiveRate: 0.0001 # 误判率
      expectedNumberOfElements: 1000000 # 预计元素个数
      needToLoad: true # 是否需要加载已有数据
    simpleSeq: # 程序记录, 不要手动修改
      start: 1000000000 # simpleSeq算法的起始值
  server:
    transferGap: 1000 # 单位ms

auth:
  password: pass # 管理员口令, 忘记密码修改这里无需重启
  jwt:
    expire: 1 # 单位小时
    secret: signature # jwt服务器签名
    issuer: short_link_sys # jwt签发者

dev:
  mysql:
    host: localhost
    port: 3306
    username: root
    password: password
    database: short_link_sys
    maxIdleConns: 10
    maxOpenConns: 100
    connMaxLifetime: 60 # minute
