mysql:
  host: localhost
  port: 3306
  username: root
  password: root
  database: test

server:
  host: localhost
  port: 8081

log:
  level: debug # debug, info, warn, error, fatal, panic
  path: ./log